artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  gcs_bucket_name: moneylion-202511010
  gcs_source_folder: raw 
  raw_files:
    - clarity_underwriting_variables.csv
    - loan.csv
    - payment.csv
  local_download_dir: artifacts/data_ingestion/raw
  gcp_credentials_path: .credentials/gcp/daring-night-475804-a8-ab772b8e37f7.json

data_transformation:
  root_dir: artifacts/data_transformation
  loan_raw: artifacts/data_ingestion/raw/loan.csv
  clarity_raw: artifacts/data_ingestion/raw/clarity_underwriting_variables.csv
  joined_local: artifacts/data_transformation/joined_df.csv

data_loading:
  root_dir: artifacts/data_loading
  local_file: artifacts/data_transformation/joined_df.csv
  gcs_target: gs://moneylion-202511010/joined_df.csv
