artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  gcs_bucket_name: moneylion-202511010
  gcs_source_folder: raw 
  raw_files:
    - clarity_underwriting_variables.csv
    - loan.csv
    - payment.csv
  local_download_dir: artifacts/data_ingestion/raw
  gcp_credentials_path: .credentials/gcp/daring-night-475804-a8-ab772b8e37f7.json

data_transformation:
  root_dir: artifacts/data_transformation
  loan_raw: artifacts/data_ingestion/raw/loan.csv
  clarity_raw: artifacts/data_ingestion/raw/clarity_underwriting_variables.csv
  joined_local: artifacts/data_transformation/joined_df.csv
  dummy_cols_path: artifacts/model_training/dummy_cols.json
  num_stats_path: artifacts/model_training/numeric_stats.json

data_loading:
  root_dir: artifacts/data_loading
  local_file: artifacts/data_transformation/joined_df.csv
  gcs_target: gs://moneylion-202511010/joined_df.csv

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  joined_csv: artifacts/data_transformation/joined_df.csv
  test_size: 0.15
  val_size: 0.15
  random_state: 517

data_embedding:
  root_dir: artifacts/data_embedding
  preproc_dir: artifacts/data_preprocessing
  train_cat: train_cat.npy
  train_num: train_num.npy
  train_y: train_y.npy
  val_cat: val_cat.npy
  val_num: val_num.npy
  val_y: val_y.npy
  vocabs: vocabs.json
  embed_matrices: embed_matrices
  embed_schema: embed_schema.json

model_training:
  root_dir: artifacts/model_training
  embed_dir: artifacts/data_embedding
  mlflow_experiment: loan-default-xgb-v1

